name: Compilation Test - Bin build & CS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-bin:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make CICD=1
    - name: make clean
      run: make clean
    - name: make fclean
      run: make fclean
    - name: makere
      run: make CICD=1 re

  build-coding-style:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Copy Dockerfile inside root
      run : cp ./.github/Dockerfile ./Dockerfile
    - name: Build coding-style tests
      run: docker build . -t cs-test --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Run basic command
      run : docker run cs-test:latest
